### ISSUE TITLE
Using Float64 type cause error. Float32 type causes slightly malformed number.

### ISSUE THREAD

**Issue by Tom-atoes** [ffrostflame/ByteNet#8]
Float64 Error: 
![image](https://github.com/ffrostflame/ByteNet/assets/69087922/ec8a5193-adcb-4fae-a2d9-f9da97511d44)

Float32 Error:
![image](https://github.com/ffrostflame/ByteNet/assets/69087922/3a02247c-9241-44e2-beab-d7a0fdb36aaa)

**Comment by ffrostflame** [comment]
Solved
